### PR TITLE
Misc atlas fixes

### LINKED ISSUE #318: Jets aren't proportional to their energy.
Like Atlantis, the jets don't have a proportional size to their energy. Both Atlantis and Phoenix jets are shown in the attached images (same xml file).
In Phoenix, id:0 and id:1 are the two leading jets.
phoenix_jet
Atlantis_jet

### LINKED ISSUE #319: Phoenix does not display photon and electron objects
Phoenix menu does not display photon and electron objects using .xml input.
On the Event data collection info tab, these object information may be viewed but they cannot be highlighted.

### PR DESCRIPTION
**Pull request by EdwardMoyse**
Includes many fixes such as:
- no longer limit jet lengths since we can scale them bb41683 (which fixes #318 )
- better handling of JiveXML objects (pt and fix cuts to match, out-of-bounds angles etc)
- handle compound objects consistently (and added electron and photon which fixes #319 )
- refactored some elements of the runge kutta

### CODE REVIEW

File: packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts [hunk 1]
```diff
@@ -150,10 +140,6 @@ export class PhoenixObjects {
       : CoordinateHelper.etaToTheta(eta);
     // Jet energy parameter can either be 'energy' or 'et'
     let length = (jetParams.energy ? jetParams.energy : jetParams.et) * 0.2;
-    // Ugh - We don't want the Jets to go out of the event display
```
Comment (9inpachi) [inline packages/phoenix-event-display/src/loaders/objects/phoenix-objects.ts:153]: Is this fine for now? I was thinking of normalizing the energy in a certain range. The differences should then be apparent and Jets won't scale more than the event display.

**Review by 9inpachi — APPROVED** [review]
